import Image from "next/image";
import {Button} from "@heroui/button";
import {Link} from "@heroui/link";

export default function Home() {
  return (
    <div className="h-[100%] w-[100%]">
      <div className = "flex justify-center items-center h-screen">
        <div style={{ background: 'radial-gradient(circle farthest-corner at 25% center, #7f1d1d, #460809, #230405,  #230405 100%)' }} className="wrapper relative overflow-clip w-6xl h-full w-full flex justify-center items-left z-10 flex-col px-10 before:absolute before:h-[60%] before:w-[40%] before:animate-[blob_30s_infinite_linear] before:rounded-full before:bg-red-900 before:opacity-40 before:blur-[60px] after:absolute after:h-[80%] after:w-[60%] after:animate-blob-reverse after:rounded-full after:bg-red-900 after:opacity-40 after:animate-[blob_20s_infinite_linear_reverse] after:left-[50%] after:top-[50%] after:blur-[60px]">
          <p className="z-10 text-white font-bold text-[60px]/20">A place to</p>
          <p className="z-10 font-bold text-[80px]/20 text-white">&gt; experiment</p>
          <p className="z-10 text-[24px]/20 text-[#dddddd]">Some fancy description here.</p>
          <Button className="z-10">Click me</Button>
        </div>
      </div>

      <div style={{ background: 'linear-gradient(to bottom, #230405, #460809,  #230405 100%)' }} className="min-h-screen h-full w-full py-[15%] px-16 flex justify-center items-center">
        <div style={{ background: 'linear-gradient(to bottom, #7f1d1d, #460809)' }} className="flex justify-center w-[85%] rounded-xl h-[100%] min-h-[90vh]">
          <div className="w-[50%] h-[100%] my-16 mx-12 flex flex-col justify-start items-start">
            <h1 className="font-bold text-[50px]/16 text-[#eeeeee]">CURRENT NEWS AND UPCOMING EVENTS</h1>
            <span className="my-4 w-[80%] border-1 border-white"></span>
            <p className="text-[#dddddd] text-[24px] font-bold">Informational Meeting FAQs are here:</p>
            <p className="text-[#dddddd] text-[16px]">Please see questions that were generated by our families during their visit.<Link href="https://docs.google.com/document/d/1r7F7TeR3H95a6tlwmRH1GOFHW3dkra3kBdLHdu43WnQ/edit?tab=t.0" underline="always">MAGNET FAQ</Link></p>


            <p className="mt-10 text-[#dddddd] text-[24px] font-bold">National Merit Semifinalists</p>
            <p className="text-[#dddddd] text-[16px]">Congratulations to Blair's 36 <b>Class of 2026 National Merit Semifinalists</b>: Safwan Ahmed, Nathaniel Bingenheimer, Kian Dhawan, Lillian Fischer, Daniel Hoang, Ethan Hua, Jeffery Ji, Leo Jin, Jesse Jing, Sophia Jones, Mehr Kaur, Ryan L. Leventhal, Cooper Li, Jason Liang, Ethan Liu, James Lozada-McBride, Gerald Lu, Riley MacArthur, Arjun Ramachandran, Justin Rosentover, Adithi Sathyanarayanan, Eric Shi, Tony Song, Christopher Tang, Gugan Thuduppathy, Kiya Tiruneh, Arthur Wang, Doris Wang, Eliana Wang, Shaun Wang, Yongle Xin, Jason Yao, Sophia Yeung, Evan Zhang, William Zhang, Ezra Zibel</p>
          </div>
          <div className="w-[50%] min-h-[300px] relative bg-green-100">
            <Image src="/assets/apple.png" fill alt="apples" className="object-cover" />
          </div>
        </div>
        
      </div>

      <div style={{ background: 'linear-gradient(to bottom, #230405, #460809,  #230405 100%)' }} className="min-h-screen h-full w-full p-16 flex justify-center items-center">
        <div style={{ background: 'linear-gradient(to bottom, #7f1d1d, #460809)' }} className="flex flex-col justify-center w-[85%] rounded-xl bg-red-900 h-[100%] min-h-[90vh] text-center items-center">
          <p className="font-bold text-[100px] text-[#eeeeee]">Magnet Mission</p>
          <div className="border-1 border-white w-[10%]"></div>
        <p className="text-[#eeeeee] w-[70%] mt-[16px]">Recognizing that education is an individual experience that depends on the unique talents and interests of each person, the mission of the Blair Magnet Program is to provide an environment in which each person's education is maximized by emphasizing the interrelationships among the disciplines, developing a repertoire of problem-solving techniques, and pursuing both independent and collaborative research projects.</p>
        <p className="text-[#eeeeee] w-[70%] mt-[16px]">To realize the above mission, the staff nurtures the special talents of its academically able students by fostering individualism, independent thinking, and self-confidence by challenging those students through a unique, diversified curriculum. The environment, structure, and content promote the self-learner concept in which students participate in constructing their own knowledge base and learn problem-solving strategies that foster the multidisciplinary approach. The scope of their education extends beyond traditional classroom boundaries as students are asked to connect with a community that includes not only parents, mentors, other students, and staff but also a physical environment as diverse as our region.</p>
        </div>
      </div>

    </div>
  );
}

// after:absolute after:h-[50%] after:w-[50%] after:animate-blob-reverse after:rounded-full after:bg-red-800 
