"use client";

import Image from "next/image";
import { Button, Link } from '@heroui/react';

//

export default function Home() {
  return (
    <div className="h-[100%] w-[100%]" style={{ background: 'linear-gradient(to bottom, #460809 80%,  #230405)' }}>
      <div className = "flex justify-center items-center h-screen">
        <div  className="wrapper relative overflow-clip w-6xl h-full w-full flex justify-center items-left z-10 flex-col px-10 before:absolute before:h-[60%] before:w-[40%] before:animate-[blob_30s_infinite_linear] before:rounded-full before:bg-red-900 before:opacity-40 before:blur-[60px] after:absolute after:h-[80%] after:w-[60%] after:animate-blob-reverse after:rounded-full after:bg-red-900 after:opacity-40 after:animate-[blob_20s_infinite_linear_reverse] after:left-[50%] after:top-[50%] after:blur-[60px] overflow-y-visible">
          <p className="z-10 text-white font-bold text-[60px]/20">A place to</p>
          <p className="z-10 font-bold text-[80px]/20 text-white">&gt; experiment</p>
          <p className="z-10 text-[20px]/20 text-[#cccccc]">Welcome to the STEM Magnet Program at Montgomery Blair High School.</p>
          <div className="flex flex-row gap-4"><Button className="z-10 bg-[#7f1d1d]" size="lg">Learn More</Button><Button className="z-10 bg-white text-[#7f1d1d]" size="lg">Apply</Button></div>
        </div>
      </div>

      {/* current news */}
      <div className="min-h-screen h-full w-full py-[15%] px-16 flex justify-center items-center z-40">
        <div style={{ background: "linear-gradient(to bottom, rgba(127,29,29,0.2)" }} className="flex justify-center w-[85%] rounded-2xl h-[100%] min-h-[90vh] shadow-xl">
          <div className="h-[100%] my-16 mx-12 flex flex-col justify-center items-center">
            <h1 className="font-bold text-[50px]/16 text-[#eeeeee] text-center">CURRENT NEWS AND UPCOMING EVENTS</h1>
            <span className="my-10 w-[80%] border-1 border-white"></span>

            <div className=" grid grid-cols-2 gap-10">
            <div className="flex flex-col gap-4 bg-[rgba(127,29,29,0.1)] rounded-xl p-8 shadow-md">
              <p className="text-[#dddddd] text-[24px] font-bold">Summer School Offerings</p>

              <p className="text-[#dddddd] text-[16px]">The 3/24 announcement from MCPS moving the last day of school to June 18th is necessary, but not sufficient to finalize our plan. <span className="font-bold">Expect factoring camp to be offered  6/22-6/26, and Magnet Geometry to be offered during the MCPS summer school window (with an option to begin early as the summer school window</span> is narrower than it has been in the past, while the content of the course remains constant). <span className="underline underline-offset-4">Factoring camp is strongly recommended for all rising 9th graders, AND is required for those who want to take our Functions course.</span> Magnet Geometry is an offering for those who have not completed Geometry in middle school.</p>
            </div>

            <div className="flex flex-col gap-4 bg-[rgba(127,29,29,0.1)] rounded-xl p-8 shadow-md">
              <p className="text-[#dddddd] text-[24px] font-bold">Informational Meeting FAQs are here:</p>

              <p className="text-[#dddddd] text-[16px]">Please see questions that were generated by our families during their visit.</p>

              <Link href="https://docs.google.com/document/d/1r7F7TeR3H95a6tlwmRH1GOFHW3dkra3kBdLHdu43WnQ/edit?tab=t.0" className="underline text-white">MAGNET FAQ<Link.Icon /></Link>
            </div>

            <div className="flex flex-col gap-4 bg-[rgba(127,29,29,0.1)] rounded-xl p-8 shadow-md">
              <p className="text-[#dddddd] text-[24px] font-bold">National Merit Semifinalists</p>
            <p className="text-[#dddddd] text-[16px]">Congratulations to Blair's 36 <b>Class of 2026 National Merit Semifinalists</b>: Safwan Ahmed, Nathaniel Bingenheimer, Kian Dhawan, Lillian Fischer, Daniel Hoang, Ethan Hua, Jeffery Ji, Leo Jin, Jesse Jing, Sophia Jones, Mehr Kaur, Ryan L. Leventhal, Cooper Li, Jason Liang, Ethan Liu, James Lozada-McBride, Gerald Lu, Riley MacArthur, Arjun Ramachandran, Justin Rosentover, Adithi Sathyanarayanan, Eric Shi, Tony Song, Christopher Tang, Gugan Thuduppathy, Kiya Tiruneh, Arthur Wang, Doris Wang, Eliana Wang, Shaun Wang, Yongle Xin, Jason Yao, Sophia Yeung, Evan Zhang, William Zhang, Ezra Zibel</p>
            </div>

            </div>
          </div>
        </div>
        
      </div>

      {/* magnet mission */}
      <div className="min-h-screen h-full w-full p-16 flex justify-center items-center">
        <div style={{ background: "linear-gradient(to bottom, rgba(127,29,29,0.2)" }} className="flex flex-col justify-center w-[85%] rounded-xl bg-red-900 h-[100%] min-h-[90vh] text-center items-center">
          <p className="font-bold text-[100px] text-[#eeeeee]">Magnet Mission</p>
          <div className="border-1 border-white w-[10%]"></div>
          <div className="flex flex-row gap-10 mx-20 my-10 items-center">
            <Image src="/assets/home 1.jpg" width={300} height={200} alt="magnet students" className="rounded-xl "></Image>
            <p className="text-[#eeeeee] w-[70%] mt-[16px] text-left">Recognizing that education is an individual experience that depends on the unique talents and interests of each person, the mission of the Blair Magnet Program is to provide an environment in which each person's education is maximized by emphasizing the interrelationships among the disciplines, developing a repertoire of problem-solving techniques, and pursuing both independent and collaborative research projects.</p>
          </div>

          <div className="flex flex-row gap-10 mx-20 my-10 items-center">
            
            <p className="text-[#eeeeee] w-[70%] mt-[16px]">To realize the above mission, the staff nurtures the special talents of its academically able students by fostering individualism, independent thinking, and self-confidence by challenging those students through a unique, diversified curriculum. The environment, structure, and content promote the self-learner concept in which students participate in constructing their own knowledge base and learn problem-solving strategies that foster the multidisciplinary approach. The scope of their education extends beyond traditional classroom boundaries as students are asked to connect with a community that includes not only parents, mentors, other students, and staff but also a physical environment as diverse as our region.</p>
            <Image src="/assets/home 2.jpg" width={300} height={100} alt="magnet students" className="rounded-xl "></Image>
          </div>
        
        
        </div>
      </div>

    </div>
  );
}

// after:absolute after:h-[50%] after:w-[50%] after:animate-blob-reverse after:rounded-full after:bg-red-800 
